### ISSUE TITLE
crashed on running

### ISSUE THREAD

**Issue by duqiaochai** [henrypijames/trackergate#2]
TypeError: Cannot read property 'length' of undefined
    at Job.parseErrRes (/root/trackergate-master/trackergate.js:330:21)
    at TrackerGate.resTracker (/root/trackergate-master/trackergate.js:444:15)
    at Socket.<anonymous> (/root/trackergate-master/trackergate.js:13:59)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)

**Comment by henrypijames** [comment]
Should be fixed now. Thx for reporting, sorry it took me so long to notice it.
